// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4JQtnk7hNI-vEqQ689XFXzqy_NxgZm0',
    appId: '1:513843689861:web:cb7b8f73658b0b4169ecec',
    messagingSenderId: '513843689861',
    projectId: 'thedaytraderfx-e823f',
    authDomain: 'thedaytraderfx-e823f.firebaseapp.com',
    storageBucket: 'thedaytraderfx-e823f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6cqhrVvOwRPgIF8Uz5U3nVIe3El6GCdM',
    appId: '1:513843689861:android:11b998f096cba9d569ecec',
    messagingSenderId: '513843689861',
    projectId: 'thedaytraderfx-e823f',
    storageBucket: 'thedaytraderfx-e823f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBst7tAXGuTKBdap4JL773d_2-9BFwCb00',
    appId: '1:513843689861:ios:b1b3d7c846342fb669ecec',
    messagingSenderId: '513843689861',
    projectId: 'thedaytraderfx-e823f',
    storageBucket: 'thedaytraderfx-e823f.appspot.com',
    iosBundleId: 'com.example.thedaytrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBst7tAXGuTKBdap4JL773d_2-9BFwCb00',
    appId: '1:513843689861:ios:668b0505f2f14bbe69ecec',
    messagingSenderId: '513843689861',
    projectId: 'thedaytraderfx-e823f',
    storageBucket: 'thedaytraderfx-e823f.appspot.com',
    iosBundleId: 'com.example.thedaytrader.RunnerTests',
  );
}
